### ISSUE TITLE
retire my name from the list

### ISSUE THREAD

**Issue by lacopinedeflipper** [velvetyne/Pictoporn#1]
hello i just want to retire my name from the list of that file because i didnt participate to it
thank you by advance
auriana

**Comment by raphaelbastide** [comment]
Thanks for the request, that should be fixed.

**Comment by lacopinedeflipper** [comment]
thank you very much

Le ven. 1 sept. 2023 à 18:23, Raphaël Bastide ***@***.***> a
écrit :
